apiVersion: v2
appVersion: v0.11.3
description: A Helm chart for deploying cluster API.
icon: https://assets.unikorn-cloud.org/assets/images/logos/dark-on-light/icon.png
name: cluster-api-provider-openstack
type: application
version: v0.3.0
