apiVersion: v2
appVersion: v1.9.4
description: A Helm chart for deploying cluster API.
icon: https://assets.unikorn-cloud.org/assets/images/logos/dark-on-light/icon.png
name: cluster-api-control-plane-kubeadm
type: application
version: v0.2.4
