capi_diagnostics_address: :8443
capi_insecure_diagnostics: false
cluster_topology: false
exp_kubeadm_bootstrap_format_ignition: false
image: registry.k8s.io/cluster-api/kubeadm-control-plane-controller:v1.7.0
