capi_diagnostics_address: :8443
capi_insecure_diagnostics: false
cluster_topology: false
exp_cluster_resource_set: false
exp_machine_pool: false
exp_machine_set_preflight_checks: false
exp_runtime_sdk: false
image: registry.k8s.io/cluster-api/cluster-api-controller:v1.7.0
