apiVersion: v2
appVersion: v1.0.0
description: A Helm chart for deploying cluster API.
icon: https://assets.unikorn-cloud.org/assets/images/logos/dark-on-light/icon.png
name: openstack-resource-controller
type: application
version: v0.2.3
